version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: bet-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
    - "5051:80"

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile
    container_name: simple-bet-backend
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8081:8081"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    container_name: simple-bet-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"
    environment:
      API_URL: http://backend:8081/api/matches

volumes:
  db-data: