name: Build & Push Docker Images

on:
  workflow_run:
    workflows: ["Java CI with Maven"]
    types:
      - completed

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set lowercase repo owner
        run: echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend image
        run: |
          docker build -f docker/backend.Dockerfile -t ghcr.io/${{ env.REPO_OWNER_LC }}/simple-bet-backend:latest .
          docker push ghcr.io/${{ env.REPO_OWNER_LC }}/simple-bet-backend:latest

      - name: Build & push frontend image
        run: |
          docker build -f docker/frontend.Dockerfile -t ghcr.io/${{ env.REPO_OWNER_LC }}/simple-bet-frontend:latest .
          docker push ghcr.io/${{ env.REPO_OWNER_LC }}/simple-bet-frontend:latest